import { setRequestLocale } from 'next-intl/server';
import styles from '../legal.module.css';

export default async function TermsOfUsePage({ params }: { params: Promise<{ locale: string }> }) {
    const { locale } = await params;
    setRequestLocale(locale);

    return (
        <main className={styles.container}>
            <h1 className={styles.title}>Terms of Use</h1>
            <span className={styles.lastUpdated}>Last Updated: December 20, 2025</span>

            <div className={styles.content}>
                <h2>1. Introduction</h2>
                <p>Welcome to <strong>BodyCoach</strong> ("we," "our," or "us"). By downloading, accessing, or using the BodyCoach mobile application (the "App"), you agree to be bound by these Terms of Use ("Terms"). If you do not agree to these Terms, please do not use the App.</p>

                <h2>2. No Medical Advice (IMPORTANT)</h2>
                <p><strong>BodyCoach is an AI-powered lifestyle and fitness coaching application, not a medical service.</strong></p>
                <ul>
                    <li><strong>Not a Doctor:</strong> The content, coaching, and advice provided by the App are for informational and educational purposes only and do not constitute medical advice, diagnosis, or treatment.</li>
                    <li><strong>Consult a Physician:</strong> You should always consult with a physician or other healthcare professional before starting any diet, exercise, or nutrition program.</li>
                    <li><strong>AI Limitations:</strong> The guidance provided by BodyCoach is generated by Artificial Intelligence. While we strive for accuracy, AI can occasionally generate incorrect, misleading, or unsafe information. You rely on the App's advice solely at your own risk.</li>
                </ul>

                <h2>3. User Accounts</h2>
                <p>To use certain features of the App, you may be required to create an account. You agree to:</p>
                <ul>
                    <li>Provide accurate and complete information.</li>
                    <li>Keep your login credentials secure.</li>
                    <li>Accept responsibility for all activities that occur under your account.</li>
                    <li>Be at least 13 years of age (or the minimum age of digital consent in your country).</li>
                </ul>

                <h2>4. Subscriptions and Payments</h2>
                <p>BodyCoach may offer subscription plans (e.g., Monthly, Yearly) granting access to premium features.</p>
                <ul>
                    <li><strong>Billing:</strong> Payments will be charged to your Apple App Store or Google Play Store account upon confirmation of purchase.</li>
                    <li><strong>Auto-Renewal:</strong> Subscriptions automatically renew unless auto-renew is turned off at least 24 hours before the end of the current period.</li>
                    <li><strong>Cancellations:</strong> You can manage or cancel your subscription in your device's Account Settings. We do not process refunds directly; please refer to the refund policies of Apple or Google.</li>
                </ul>

                <h2>5. User Content and Conduct</h2>
                <p>You retain ownership of the photos, data, and text you upload to the App ("User Content"). By uploading content, you grant us a license to use it solely for the purpose of operating and improving the App (e.g., analyzing food photos).</p>
                <p>You agree <strong>not</strong> to:</p>
                <ul>
                    <li>Use the App for any illegal purpose.</li>
                    <li>Harass, abuse, or harm another person or the AI system.</li>
                    <li>Reverse engineer or attempt to extract the source code of the App.</li>
                </ul>

                <h2>6. Intellectual Property</h2>
                <p>All intellectual property rights in the App, including the software, design, logos, and AI algorithms, are owned by <strong>Minsik Chae</strong> or our licensors.</p>

                <h2>7. Limitation of Liability</h2>
                <p>To the fullest extent permitted by law, <strong>Minsik Chae</strong> shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to personal injury, loss of data, or financial loss, arising out of your use of or inability to use the App.</p>

                <h2>8. Changes to Terms</h2>
                <p>We reserve the right to modify these Terms at any time. We will notify you of any changes by posting the new Terms on this page. Your continued use of the App constitutes acceptance of the changes.</p>

                <h2>9. Governing Law</h2>
                <p>These Terms shall be governed by and construed in accordance with the laws of the <strong>Republic of Korea</strong>, without regard to its conflict of law provisions.</p>

                <h2>10. Contact Us</h2>
                <p>If you have any questions about these Terms, please contact us at:</p>
                <ul>
                    <li><strong>Email:</strong> kicoa24@gmail.com</li>
                </ul>
            </div>
        </main>
    );
}
